
##################################################################################################
# Details service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: api-pruebas
  labels:
    app: api-pruebas
    service: api-pruebas
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: api-pruebas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pruebas-v1
  labels:
    app: api-pruebas
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pruebas
      version: v1
  template:
    metadata:
      labels:
        app: api-pruebas
        version: v1
    spec:
      serviceAccountName: api-pruebas
      containers:
      - name: api-pruebas
        image: mexparedes/api-pruebas:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
##################################################################################################
#