version: '3.7'

networks:
  myNetwork:
    name: myNetwork

services:
  app:
    container_name: orquestador 
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
    - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - myNetwork
